export const ROOM_OPTIONS = [
  "Salon",
  "Cuisine",
  "Salle à manger",
  "Chambre",
  "Salle de bain",
  "WC",
  "WC séparé",
  "Bureau",
  "Terrasse",
  "Balcon",
  "Jardin",
  "Parking",
  "Garage",
  "Buanderie",
  "Cave",
  "Mezzanine",
];

export const AMENITY_OPTIONS = [
  "Wifi",
  "Télévision",
  "Climatisation",
  "Chauffage",
  "Lave-linge",
  "Sèche-linge",
  "Lave-vaisselle",
  "Cuisine équipée",
  "Micro-ondes",
  "Cafetière",
  "Bouilloire",
  "Grille-pain",
  "Parking",
  "Piscine",
  "Jacuzzi",
  "Cheminée",
  "Barbecue",
  "Ascenseur",
  "Animaux acceptés",
  "Fumeurs autorisés",
  "Draps fournis",
  "Arrivée autonome",
  "Accès PMR",
];
